# Generated by Django 4.1.6 on 2023-02-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('validity', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.company')),
            ],
        ),
    ]
